[workspace.package]
version = "0.1.0"
authors = ["GLV_off <glv.off@mail.ru>"]
edition= "2024"
license = "MIT"

[workspace]
resolver = "2"
members = [
    "crates/fs_cli", 
    "crates/fs_lib",
    "crates/fs_frontend"
]

[workspace.dependencies]
clap = { version = "4.6.7", features = ["derive"] }
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

# Read the optimization guideline for more details: https://tauri.app/concept/size/#cargo-configuration
[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = true
